import { Teacher } from "@/lib/types";
export const teachers: Teacher[] = [
  {
    id: 1,
    name: "Sarah Jenkins",
    title: "İngilizce Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=1",
    price: 850,
    rating: 4.9,
    reviewCount: 120,
    description: "Amerikalı eğitmenden konuşma pratiği ve TOEFL/IELTS sınavlarına hazırlık dersleri.",
    tags: ["İngilizce", "Konuşma", "TOEFL"],
    isTopRated: true,
  },
  {
    id: 2,
    name: "Davut Çelik",
    title: "Matematik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=2",
    price: 1000,
    rating: 5.0,
    reviewCount: 85,
    description: "LGS, YKS ve üniversite seviyesinde Calculus dersleri. Karmaşık konuları basitleştirerek anlatıyorum.",
    tags: ["Matematik", "Geometri", "YKS"],
    isTopRated: true,
  },
  {
    id: 3,
    name: "Elif Yılmaz",
    title: "Yazılım Uzmanı",
    imageUrl: "https://i.pravatar.cc/150?u=3",
    price: 1200,
    rating: 4.8,
    reviewCount: 42,
    description: "Sıfırdan ileri seviyeye React, Next.js ve Tailwind CSS eğitimi. Modern web projeleri geliştirmeyi öğrenin.",
    tags: ["Yazılım", "React", "Frontend"],
    isTopRated: false,
  },
  {
    id: 4,
    name: "Ahmet Keskin",
    title: "Fizik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=6",
    price: 800,
    rating: 4.6,
    reviewCount: 22,
    description: "ODTÜ Fizik mezunundan AYT/TYT sınavlarına yönelik detaylı konu anlatımı ve soru çözümü.",
    tags: ["Fizik", "Fen", "AYT"],
    isTopRated: false,
  },
  {
    id: 5,
    name: "Emel Yıldız",
    title: "Kimya Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=11",
    price: 700,
    rating: 4.7,
    reviewCount: 19,
    description: "Organik ve Anorganik Kimya konularında uzman desteği. Periyodik tabloyu ezberlemeyin, mantığını anlayın.",
    tags: ["Kimya", "Fen", "AYT"],
    isTopRated: false,
  },
  {
    id: 6,
    name: "Mustafa Can",
    title: "Yazılım Eğitmeni",
    imageUrl: "https://i.pravatar.cc/150?u=8",
    price: 1100,
    rating: 5.0,
    reviewCount: 56,
    description: "Python programlama, Pandas ve Yapay Zeka temelleri. Uygulamalı projelerle eğitim.",
    tags: ["Yazılım", "Python", "Veri Bilimi"],
    isTopRated: true,
  },
  {
    id: 7,
    name: "Zeynep Kaya",
    title: "Biyoloji Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=9",
    price: 600,
    rating: 4.4,
    reviewCount: 12,
    description: "Lise ve üniversite sınavlarına hazırlık için biyoloji özel dersleri. Sistemler konusuna hakim olun.",
    tags: ["Biyoloji", "TYT", "Anatomi"],
    isTopRated: false,
  },
  {
    id: 8,
    name: "Mehmet Özkan",
    title: "Matematik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=27",
    price: 900,
    rating: 4.7,
    reviewCount: 55,
    description: "Üçgenler, Analitik Geometri ve Katı Cisimler. Görmeyi öğreten geometri ağırlıklı matematik dersleri.",
    tags: ["Matematik", "Geometri", "YKS"],
    isTopRated: false,
  },
  {
    id: 9,
    name: "Selin Tekin",
    title: "Fizik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=28",
    price: 1100,
    rating: 5.0,
    reviewCount: 18,
    description: "Mühendislik öğrencileri için Fizik 101/102, Statik ve Termodinamik dersleri.",
    tags: ["Fizik", "Üniversite", "Mühendislik"],
    isTopRated: true,
  },
  {
    id: 10,
    name: "Burak Yılmaz",
    title: "Kimya Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=29",
    price: 650,
    rating: 4.6,
    reviewCount: 24,
    description: "Lise seviyesi kimya takviye ve sınavlara hazırlık. Mol kavramı ve kimyasal hesaplamalar.",
    tags: ["Kimya", "Fen", "TYT"],
    isTopRated: false,
  },
  {
    id: 11,
    name: "Deniz Arslan",
    title: "İngilizce Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=30",
    price: 750,
    rating: 4.8,
    reviewCount: 90,
    description: "Akademik kariyer hedefleyenler için sınav stratejileri ve gramer odaklı İngilizce eğitimi (YDS/YÖKDİL).",
    tags: ["İngilizce", "YDS", "Akademik"],
    isTopRated: true,
  },
  {
    id: 12,
    name: "Kemal Vural",
    title: "Matematik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=31",
    price: 850,
    rating: 4.9,
    reviewCount: 40,
    description: "8. sınıf öğrencileri için özel LGS programı. Matematik netlerinizi artırın.",
    tags: ["Matematik", "LGS", "Sınav"],
    isTopRated: true,
  },
  {
    id: 13,
    name: "Beren Saatçi",
    title: "Biyoloji Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=32",
    price: 700,
    rating: 4.7,
    reviewCount: 15,
    description: "Sistemler, Ekoloji ve Kalıtım konularında detaylı anlatım.",
    tags: ["Biyoloji", "AYT", "Fen"],
    isTopRated: false,
  },
  {
    id: 14,
    name: "Onur Çevik",
    title: "Fizik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=33",
    price: 600,
    rating: 4.5,
    reviewCount: 10,
    description: "9. ve 10. sınıf fizik konuları. Elektrik, Optik ve Hareket üniteleri.",
    tags: ["Fizik", "Lise", "Fen"],
    isTopRated: false,
  },
  {
    id: 15,
    name: "Seda Nur",
    title: "Matematik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=34",
    price: 950,
    rating: 5.0,
    reviewCount: 28,
    description: "Her seviyeye uygun matematik dersleri. Ödev takibi ve düzenli deneme sınavları.",
    tags: ["Matematik", "Eğitim", "Özel Ders"],
    isTopRated: true,
  },
  {
    id: 16,
    name: "Ayşe Yılmaz",
    title: "Matematik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=26",
    price: 600,
    rating: 4.8,
    reviewCount: 32,
    description: "İlkokul ve ortaokul öğrencileri için matematik takviye. Yeni nesil soru çözümleri.",
    tags: ["Matematik", "LGS", "İlköğretim"],
    isTopRated: true,
  },
  {
    id: 17,
    name: "Caner Erkin",
    title: "Yazılım Uzmanı",
    imageUrl: "https://i.pravatar.cc/150?u=36",
    price: 1300,
    rating: 4.9,
    reviewCount: 20,
    description: "Java ve Spring Boot ile Backend geliştirme dersleri. Kurumsal mimariler üzerine eğitim.",
    tags: ["Yazılım", "Java", "Backend"],
    isTopRated: false,
  },
  {
    id: 18,
    name: "Merve Aydın",
    title: "Biyoloji Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=37",
    price: 550,
    rating: 4.3,
    reviewCount: 8,
    description: "Ortaokul Fen Bilgisi ve Lise Biyoloji takviye dersleri.",
    tags: ["Biyoloji", "Fen", "Lise"],
    isTopRated: false,
  },
  {
    id: 19,
    name: "Ozan Çelik",
    title: "Kimya Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=38",
    price: 850,
    rating: 4.8,
    reviewCount: 16,
    description: "AYT Kimya konularında nokta atışı anlatımlar. Gazlar, Çözeltiler ve Enerji konuları.",
    tags: ["Kimya", "AYT", "Sınav"],
    isTopRated: true,
  },
  {
    id: 20,
    name: "John Smith",
    title: "İngilizce Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=39",
    price: 1100,
    rating: 5.0,
    reviewCount: 45,
    description: "Londralı eğitmenden Business English ve iş mülakatlarına hazırlık dersleri.",
    tags: ["İngilizce", "İş İngilizcesi", "Konuşma"],
    isTopRated: true,
  },
  {
    id: 21,
    name: "Volkan Kaya",
    title: "Fizik Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=40",
    price: 750,
    rating: 4.6,
    reviewCount: 30,
    description: "YKS Fizik kampı. Simülasyonlarla zenginleştirilmiş ders anlatımı.",
    tags: ["Fizik", "YKS", "Teknoloji"],
    isTopRated: false,
  },
  {
    id: 22,
    name: "Aslı Genç",
    title: "Yazılım Eğitmeni",
    imageUrl: "https://i.pravatar.cc/150?u=41",
    price: 900,
    rating: 4.7,
    reviewCount: 14,
    description: "HTML, CSS ve JavaScript ile web geliştirmeye giriş. Kendi web sitenizi yapın.",
    tags: ["Yazılım", "Web", "Frontend"],
    isTopRated: false,
  },
  {
    id: 23,
    name: "Sevgi Demir",
    title: "Kimya Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=42",
    price: 600,
    rating: 4.5,
    reviewCount: 10,
    description: "9. ve 10. sınıf kimya müfredatına uygun dersler.",
    tags: ["Kimya", "Lise", "Okul"],
    isTopRated: false,
  },
  {
    id: 24,
    name: "Hakan Yılmaz",
    title: "Biyoloji Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=43",
    price: 800,
    rating: 4.9,
    reviewCount: 35,
    description: "Tıp fakültesi öğrencisinden biyoloji ve fizyoloji dersleri.",
    tags: ["Biyoloji", "Tıp", "Fen"],
    isTopRated: true,
  },
  {
    id: 25,
    name: "Meltem Koç",
    title: "İngilizce Öğretmeni",
    imageUrl: "https://i.pravatar.cc/150?u=44",
    price: 600,
    rating: 4.6,
    reviewCount: 22,
    description: "Çocuklar için oyunlarla İngilizce eğitimi. Eğlenceli ve öğretici dersler.",
    tags: ["İngilizce", "Çocuk", "Eğitim"],
    isTopRated: false,
  },
];
