export const TeacherDetails = [
  {
    id: 1,
    name: "Enes Yurtveren",
    field: "Matematik",
    description: "Lise ve üniversite düzeyinde, analitik düşünceyi geliştiren sınav odaklı matematik ve geometri eğitimi.",
    price: 1300,
    rating: 4.8,
    imageUrl: "/home/featured/mathematic.png",
    topics: ["Calculus", "İntegral", "Türev", "Lineer Cebir"],
  },
  {
    id: 2,
    name: "Eren Köyan",
    field: "Yazılım",
    description: "Sektör tecrübesiyle sıfırdan ileri seviyeye modern yazılım geliştirme ve temiz kod prensipleri.",
    price: 1450,
    rating: 4.9,
    imageUrl: "/home/featured/software.png",
    topics: ["C#", ".NET Core", "OOP", "Entity Framework"],
  },
  {
    id: 3,
    name: "Yusuf Ural",
    field: "Fizik & Mühendislik",
    description: "Mühendislik öğrencileri için zorlu fizik konularını basitleştiren, proje destekli akademik eğitim.",
    price: 1500,
    rating: 4.7,
    imageUrl: "/home/featured/physic.png",
    topics: ["Mukavemet", "Akışkanlar", "Termodinamik", "Statik"],
  },
  {
    id: 4,
    name: "Maide Nur",
    field: "İngilizce",
    description: "Yurt dışı eğitim tecrübesi ile konuşma pratiği ve akademik sınavlara yönelik yoğunlaştırılmış dersler.",
    price: 1100,
    rating: 4.9,
    imageUrl: "/home/featured/english.png",
    topics: ["Speaking", "Academic Writing", "IELTS", "Grammar"],
  },
  {
    id: 5,
    name: "Sude Şengül",
    field: "Müzik",
    description: "Konservatuar mezunu eğitmen eşliğinde her yaş grubu için piyano, solfej ve müzik teorisi dersleri.",
    price: 1150,
    rating: 4.8,
    imageUrl: "/home/featured/music.png",
    topics: ["Piyano", "Solfej", "Müzik Teorisi", "Online Ders"],
  },
];
